export {default as Welcome} from './pages/welcome'
export {default as CreateWard} from './pages/create-ward'
// export {default as Ward} from './pages/ward'
// export {default as Patient} from './pages/patient'
// export {default as WardList} from './pages/ward-list'
// export {default as SubmitPatient} from './pages/submit-patient'
