export {default as Welcome} from './pages/welcome'
export {default as CreateWard} from './pages/create-ward'
export {default as AdmitPatient} from './pages/admit-patient/index'
export {default as WardList} from './pages/wards'
export {default as Ward} from './pages/ward'
export {default as SearchPatient} from './pages/search-patients'
export {default as Add} from './pages/add'
export {default as Patient} from './pages/patient'
