export {default as Welcome} from './pages/welcome'
export {default as CreateWard} from './pages/create-ward'
export {default as CreatePatient} from './pages/create-patient'
export {default as WardList} from './pages/wards'
export {default as Ward} from './pages/ward'
export {default as SearchPatient} from './pages/search-patients'
// export {default as Patient} from './pages/patient'
